### PR TITLE
[EAK-299] Website first impl

### PR DESCRIPTION
**Pull request by ala-n**
Closes: #299

### CODE REVIEW

**Comment by ala-n** [comment]
Should be merged with squash option

**Comment by abarmina** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by NastaLeo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by liubou-masiuk — APPROVED** [review]

**Comment by lmasiuk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lmasiuk** [comment]
recheck

**Comment by Bogdan9817** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by abarmina — APPROVED** [review]

**Pull request merged**
