### PR TITLE
[Tech] Merged release-2.0.7 branch to master

### PR DESCRIPTION
**Pull request by smiakchilo**

### CODE REVIEW

**Comment by AliakseiKaliada** [comment]
recheck

**Comment by AliakseiKaliada** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AliakseiKaliada** [comment]
recheck

**Comment by AliakseiKaliada** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by AliakseiKaliada** [comment]
recheck

**Comment by AliakseiKaliada** [comment]
**recheck**

**Comment by smiakchilo** [comment]
recheckcla

**Pull request merged**
